### ISSUE TITLE
URL in .repo file downloaded from staging repo points to production repo

### ISSUE THREAD

**Issue by roobre** [newrelic/integrations-pkg-test-action#17]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

For Suse and Centos, we download a `.repo` file containing the repo specification. This file is downloaded from staging or production repo correctly, but in either case the file itself is pointing to the prod repo.

https://github.com/newrelic/integrations-pkg-test-action/blob/90463b71def1cc782557b8ab354a4fab3412d03f/linux/helper_centos.sh#L6-L10

This has proven to be cumbersome in the past (e.g. by having to replace the cached fronted URL with a non-cacheable one.

We could get rid of this download and populate the file ourselves from the script.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
